---
apiVersion: v1
kind: Service
metadata:
  name: myhero-app
  labels:
    app: myhero
    tier: app
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: myhero
    tier: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhero-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhero
      tier: app
  template:
    metadata:
      labels:
        app: myhero
        tier: app
    spec:
      containers:
      - name: myhero-app
        image: juliocisco/pi_myhero_app:latest
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
          - name: myhero_mqtt_host
            value: myhero-mosca
          - name: myhero_mqtt_port
            value: "1883"
          - name: myhero_app_mode
            value: direct
          - name: myhero_data_srv
            value: myhero-data
          - name: myhero_data_key
            value: SecureData
          - name: myhero_app_key
            value: SecureApp
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 48M
      restartPolicy: Always
