apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhero-ernst
  namespace: myhero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhero
      tier: ernst
  template:
    metadata:
      labels:
        app: myhero
        tier: ernst
    spec:
      containers:
      - name: myhero-ernst
        image: juliocisco/myhero-ernst:latest
        env:
          - name: myhero_mqtt_host
            value: myhero-mosca
          - name: myhero_mqtt_port
            value: "1883"
          - name: myhero_data_srv
            value: myhero-data
          - name: myhero_data_key
            value: SecureData
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 32M
      restartPolicy: Always
